using System.Threading.Tasks;
using Grpc.Core;
using NexusSentinel.Shared.Protos; // Comes from the NexusSentinel.Shared project
using Confluent.Kafka;
using System.Text.Json;

namespace NexusSentinel.Ingestion.Services;

// Implements the gRPC service defined in the NexusSentinel.Shared project
// Base class is generated by the .proto file
public class TelemetryIngestionService : TelemetryService.TelemetryServiceBase
{
    private readonly ILogger<TelemetryIngestionService> _logger;
    private readonly IProducer<string, string> _producer;
    public TelemetryIngestionService(ILogger<TelemetryIngestionService> logger, IProducer<string, string> producer)
    {
        _logger = logger;
        _producer = producer;
    }

// Client Streaming method: Device continuously sends multiple messages, Server sends one ack after all messages are received
    public override async Task<TelemetryAck> StreamTelemetry(IAsyncStreamReader<TelemetryRecord> requestStream, ServerCallContext context)
    {
        // Read all messages from the stream until the client closes the connection
        await foreach(var record in requestStream.ReadAllAsync())
        {
            // For now we just log the data, but later we can add more processing
            _logger.LogInformation($"Received Data -> Device: {record.DeviceId} Temp: {record.Temperature:F2} Time: {record.Timestamp}");

            // Send the data to Kafka
            // Performance Note: Ingestion service uses 'await' to produce (Fire-and-forget) faster. 
            // However, to ensure data integrity, ProduceAsync usage is also common. 
            // Currently using synchronous Produce, which buffers and sends in the background.
            var jsonPayload = JsonSerializer.Serialize(record);
            _producer.Produce("telemetry", new Message<string, string>
            {
                Key = record.DeviceId,
                Value = jsonPayload
            });
        }

        // Return an acknowledgment to the client after all messages are processed
        return new TelemetryAck { Success = true, Message = "All telemetry data processed successfully" };
    }
}