using System.Threading.Tasks;
using Grpc.Core;
using NexusSentinel.Shared.Protos; // Comes from the NexusSentinel.Shared project

namespace NexusSentinel.Ingestion.Services;

// Implements the gRPC service defined in the NexusSentinel.Shared project
// Base class is generated by the .proto file
public class TelemetryIngestionService : TelemetryService.TelemetryServiceBase
{
    private readonly ILogger<TelemetryIngestionService> _logger;
    public TelemetryIngestionService(ILogger<TelemetryIngestionService> logger)
    {
        _logger = logger;
    }

// Client Streaming method: Device continuously sends multiple messages, Server sends one ack after all messages are received
    public override async Task<TelemetryAck> StreamTelemetry(IAsyncStreamReader<TelemetryRecord> requestStream, ServerCallContext context)
    {
        // Read all messages from the stream until the client closes the connection
        await foreach(var record in requestStream.ReadAllAsync())
        {
            // For now we just log the data, but later we can add more processing
            _logger.LogInformation($"Received Data -> Device: {record.DeviceId} Temp: {record.Temperature} Time: {record.Timestamp}");
        }

        // Return an acknowledgment to the client after all messages are processed
        return new TelemetryAck { Success = true, Message = "All telemetry data processed successfully" };
    }
}