<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-NexusSentinel.Processor-1b39e2c9-cdfe-4bd3-9f88-8e46c04a3353</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.13.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.12" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusSentinel.Shared\NexusSentinel.Shared.csproj" />
  </ItemGroup>
</Project>
