services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: nexus-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: nexus-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1 # ID of this server in the cluster
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Address of the coordinator
      
      # CRITICAL: Two listeners. 
      # 1. 'PLAINTEXT' for YOU (Host machine) -> localhost:9092
      # 2. 'PLAINTEXT_INTERNAL' for Docker Containers -> kafka:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      
      # Maps the listener names to security protocols (None/Plaintext for dev)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      
      # Which listener represents internal broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      
      # Must be 1 for single-node. Default is 3, which fails if you have only 1 broker.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:alpine
    container_name: nexus-redis
    ports:
      - "6379:6379"

  processor:
    build:
      context: ../
      dockerfile: src/NexusSentinel.Processor/Dockerfile
    container_name: nexus-processor
    restart: always
    environment:
      - Kafka__BootstrapServers=kafka:29092
      - Redis__ConnectionString=redis:6379
      - Kafka__GroupId=processor-group-1
      - Kafka__Topic=telemetry
    depends_on:
      - kafka
      - redis