services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: nexus-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: nexus-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1 # ID of this server in the cluster
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Address of the coordinator
      
      # CRITICAL: Two listeners. 
      # 1. 'PLAINTEXT' for YOU (Host machine) -> localhost:9092
      # 2. 'PLAINTEXT_INTERNAL' for Docker Containers -> kafka:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      
      # Maps the listener names to security protocols (None/Plaintext for dev)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      
      # Which listener represents internal broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      
      # Must be 1 for single-node. Default is 3, which fails if you have only 1 broker.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:alpine
    container_name: nexus-redis
    ports:
      - "6379:6379"

  simulator:
    build:
      context: ../
      dockerfile: src/NexusSentinel.IoTSimulator/dockerfile
    container_name: nexus-simulator
    restart: always
    environment:
      # This is required for the simulator to connect to the ingestion service inside the docker network
      - IngestionServerUrl=http://ingestion:8080
    depends_on:
      - ingestion

  ingestion:
    build:
      # context is the path to the directory that contains the Dockerfile 
      context: ../
      dockerfile: src/NexusSentinel.Ingestion/Dockerfile
    container_name: nexus-ingestion
    # restart always means that if the container crashes, it will be restarted automatically
    restart: always
    environment:
      # It is not 9092 because we are using the internal listener PLAINTEXT_INTERNAL since we are inside the docker network
      - Kafka__BootstrapServers=kafka:29092
    ports:
      # No need to expose ports since ingestion is accessed from inside the docker network
      # But if we want to access it from outside the docker network, we can expose it
      # - "5000:8080"
      []
    depends_on:
      # kafka is the name of the service in the docker-compose.yml file
      - kafka

  processor:
    build:
      context: ../
      dockerfile: src/NexusSentinel.Processor/Dockerfile
    container_name: nexus-processor
    restart: always
    environment:
      - Kafka__BootstrapServers=kafka:29092
      - Redis__ConnectionString=redis:6379
      - Kafka__GroupId=processor-group-1
      - Kafka__Topic=telemetry
    depends_on:
      - kafka
      - redis

  dashboard:
    build:
      context: ../
      dockerfile: src/NexusSentinel.Dashboard/Dockerfile
    container_name: nexus-dashboard
    restart: always
    environment:
      # This is required for the dashboard to connect to the redis inside the docker network
      # ConnectionStrings__Redis translates to ConnectionStrings:Redis in the appsettings.json file
      - ConnectionStrings__Redis=redis:6379
      # It must be changed to Production when deploying to production
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:8080"
    depends_on:
      - redis