FROM mcr.microsoft.com/dotnet/runtime:9.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/NexusSentinel.IoTSimulator/NexusSentinel.IoTSimulator.csproj", "src/NexusSentinel.IoTSimulator/"]
COPY ["src/NexusSentinel.Shared/NexusSentinel.Shared.csproj", "src/NexusSentinel.Shared/"]
RUN dotnet restore "src/NexusSentinel.IoTSimulator/NexusSentinel.IoTSimulator.csproj"
COPY . .
WORKDIR "/src/src/NexusSentinel.IoTSimulator"
RUN dotnet build "NexusSentinel.IoTSimulator.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "NexusSentinel.IoTSimulator.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NexusSentinel.IoTSimulator.dll"]